version: '3.9'

services:
  api:
    container_name: oshizukani-api
    build: ./docker/api
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    command: sh -c "yarn start"

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      POSTGRES_DB: oshizukani-dev
