version: '3.9'
volumes:
  oshizukani-postgres-data:
  oshizukani-nestjs-node-modules:

services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      POSTGRES_DB: oshizukani-dev
    volumes:
      - oshizukani-postgres-data:/var/lib/postgresql/data

  api:
    container_name: oshizukani-api
    build: ./docker/api
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
      - oshizukani-nestjs-node-modules:/app/node_modules
      # - nestjs-dist:/app/dist
  # command: sh -c "yarn install && yarn start"
